// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQEz0z5boshkcjoYCFDMH40aQTPteKB6Q',
    appId: '1:817543314376:web:a42a613ef405ecd0fd5efd',
    messagingSenderId: '817543314376',
    projectId: 'fir-new-7de6b',
    authDomain: 'fir-new-7de6b.firebaseapp.com',
    databaseURL: 'https://fir-new-7de6b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-new-7de6b.firebasestorage.app',
    measurementId: 'G-6FLF0TKCZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjHuPb5zAz7T2y_EU8OyWGIt4cWYhxqZM',
    appId: '1:817543314376:android:d6ce978735b2f440fd5efd',
    messagingSenderId: '817543314376',
    projectId: 'fir-new-7de6b',
    databaseURL: 'https://fir-new-7de6b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-new-7de6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRcALKH9AGRIP8Xi9a2vjkGp-1HtR--Pk',
    appId: '1:817543314376:ios:d2f99b1b75d8b49efd5efd',
    messagingSenderId: '817543314376',
    projectId: 'fir-new-7de6b',
    databaseURL: 'https://fir-new-7de6b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-new-7de6b.firebasestorage.app',
    iosBundleId: 'com.example.allProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRcALKH9AGRIP8Xi9a2vjkGp-1HtR--Pk',
    appId: '1:817543314376:ios:d2f99b1b75d8b49efd5efd',
    messagingSenderId: '817543314376',
    projectId: 'fir-new-7de6b',
    databaseURL: 'https://fir-new-7de6b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-new-7de6b.firebasestorage.app',
    iosBundleId: 'com.example.allProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQEz0z5boshkcjoYCFDMH40aQTPteKB6Q',
    appId: '1:817543314376:web:165b08547244b99afd5efd',
    messagingSenderId: '817543314376',
    projectId: 'fir-new-7de6b',
    authDomain: 'fir-new-7de6b.firebaseapp.com',
    databaseURL: 'https://fir-new-7de6b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-new-7de6b.firebasestorage.app',
    measurementId: 'G-4QC0Z8K8PH',
  );
}
